name: Code Review with ChatGPT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: sudo apt-get install jq

      - name: Coletar Mudanças no Código
        run: |
          git diff HEAD~1 HEAD > code_changes.diff
          echo "Diff gerado:"
          cat code_changes.diff

      - name: Enviar Código para Revisão no ChatGPT
        run: |
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "Você é um especialista em revisão de código. Dê feedbacks detalhados, apontando melhorias, erros e boas práticas."},
                {"role": "user", "content": "Revise o seguinte código e forneça feedbacks de melhorias:\n\n" + "$(cat code_changes.diff)"}
              ],
              "max_tokens": 500
            }')

          echo "## Feedback do ChatGPT:" > review_feedback.md
          echo "$RESPONSE" | jq -r '.choices[0].message.content' >> review_feedback.md

      - name: Adicionar Comentário no Pull Request (se aplicável)
        if: github.event_name == 'pull_request'
        run: |
          COMMENT=$(cat review_feedback.md)
          curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT\"}"
